package mapinterface.hashmap;

import java.util.HashMap;
import java.util.IdentityHashMap;
import java.util.Map;

public class IdentityHashMapImplementation {
    // in normal hashmap if hashCode method is overridden in a class hashCode will be generated 
    // based on that, and if not it will be based on Object class hashCode implementation that is on the
    // memory address of that object

    // but in case of identity hashmap it does not matter if the hashCode function is overridden or not 
    // the hasCode generated by the HashFunction will always depend upon Object class method implementation
    // hence it will always depend upon memory address of that object
    public static void main(String[] args) {
        Map<String, Integer> map = new HashMap<>();
        Map<String, Integer> map2 = new IdentityHashMap<>();

        String key1 = new String("key");
        String key2 = new String("key");

        System.out.println("Identity hashcode of key1: " + System.identityHashCode(key1));
        System.out.println("Identity hashcode of key2: " + System.identityHashCode(key2));

        System.out.println("hashcode of key1: " + key1.hashCode());
        System.out.println("hashcode of key2: " + key2.hashCode());

        System.out.println("Using equals: " + key1.equals(key2));
        System.out.println("Using ==: " + key1.equals(key2));

        map.put(key1, 1);
        map.put(key2, 2);
        System.out.println("Normal HashMap: " + map);
        
        map2.put(key1, 1);
        map2.put(key2, 2);
        System.out.println("Identity HashMap: " + map2);
    }
}
